baseURL = "http://capoeirafirenze.com/"
languageCode = "it-IT"
title = "Capoeria Axè"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "it"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[languages]
  [languages.it]
    contentDir = "content/it"
    languageName = "Italiano"
    weight = 10
  [languages.br]
    contentDir = "content/br"
    languageName = "Brasileiro"
    weight = 20
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 30

[params]
  custom_css = ["css/custom.css"]
  favicon = "images/favicon.ico"
  description = "Capoeira Axè Firenze"
  facebook = "https://www.facebook.com/axefirenzecapoeira/"
  twitter = ""
  instagram = "https://www.instagram.com/capoeiraaxe/"
  youtube = "https://www.youtube.com/results?search_query=mestre+boca+nua"
  github = "https://github.com/sap-nocops/capoeirafirenze.com"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  background_color_class = "bg-axe-blue"
  featured_image = "/images/gruppo.jpg"
